math-atlas/math-atlas

AtlasBase/Clint/atlas-thr.base
AtlasBase/Students/atlas-cbc.base
AtlasBase/Students/fact-amm.base

bcamm_getrf should be working now with bcswp.

Fixed bcswp. Fixed to use new copy routines and CBC2D routines.

---

iFKO/FKO/include/fko.h
iFKO/FKO/include/fko_arch.h
iFKO/FKO/include/fko_inst.h
iFKO/FKO/include/fko_optloop.h
iFKO/FKO/include/fko_symtab.h
iFKO/FKO/src/arch.c
iFKO/FKO/src/fko.c
iFKO/FKO/src/l2a.c
iFKO/FKO/src/optloop.c
iFKO/FKO/src/optreg.c
iFKO/FKO/src/optsimd.c
iFKO/FKO/src/symtab.c

update with the fixed for many bugs.

Update for iFKO

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/kernel/ClintWhaley/ATL_damm12x4x1_aarch64-A53.S
AtlasBase/kernel/ClintWhaley/ATL_damm12x4x6_aarch64-A57.S
AtlasBase/kernel/ClintWhaley/clint_am.base
AtlasBase/make.base

The second kernel for A57 (cleanup) is removed for now since the A53 kernel was chosen to be the best on xgene1.

Added the kernels for Cortex-A57 and Cortex-A53.

---

iFKO/FKO/include/fko.h
iFKO/FKO/include/fko_optloop.h
iFKO/FKO/include/fko_optsimd.h
iFKO/FKO/include/fko_types.h
iFKO/FKO/src/arch.c
iFKO/FKO/src/fko.c
iFKO/FKO/src/hil_gram.y
iFKO/FKO/src/hil_lex.l
iFKO/FKO/src/optloop.c
iFKO/FKO/src/optmisc.c
iFKO/FKO/src/optsimd.c

This update includes: 
1. new fko flags for auto-vectorizatrion (-vec, -ivec, -bvec, -vecapproach).
2. new markup support for whole routine.
3. some complicated bug fixed.

New FKO flags, Routine markup and bug fixed

---

AtlasBase/Clint/fko_atlas-mmkg.base
iFKO/FKO/src/arch.c
iFKO/FKO/src/fko.c
iFKO/FKO/src/l2a.c
iFKO/FKO/src/optloop.c
iFKO/FKO/src/optreg.c
iFKO/FKO/src/optsimd.c
iFKO/FKO/src/symtab.c

reflects the last changes made while in LSU: 
1. several minor bug fixes 
2. added some extra checking

last changes while working in LSU

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/l3micro.base
AtlasBase/Clint/micro-cpg.base

1. bugfix to support gemm copy using micro-cpg.base
2. remove specific kernels for syrk to install ATLAS

Bugfixed to support gemm copy using new basefile

---

AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/l3micro.base
AtlasBase/Clint/micro-cpg.base

1. updated micro-cpg.base to make it more readable 
2. fixed a typo atlas-make.base
3. disabled new syrk and enabled syrk_APR to pass the make check for now

updated copy generator to make it readable

---

AtlasBase/Clint/l3micro.base

although git doesn't show all the changes: 
1. changes in atlas-ammm.base to fix the header and makefile for syrk/herk
2. changes in l3micro.base to fix compilation issues
2. still make check failed in drteeth, so enabled syrk_APR

syrk related fixes

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/trmm-micro.base
iFKO/FKO/src/fko.c
iFKO/FKO/src/flow.c
iFKO/FKO/src/hil_gram.y
iFKO/FKO/src/optreg.c
iFKO/FKO/src/optsimd.c
iFKO/FKO/src/vars.c

Optimized degenerate cases (e.g., N=1, M=1) specially (and skipping calling micro kernel for them).

Optimize degenerate cases for micro trmm

---

AtlasBase/Clint/atlas-make.base
iFKO/FKO/src/fko.c
iFKO/FKO/src/flow.c
iFKO/FKO/src/hil_gram.y
iFKO/FKO/src/optreg.c
iFKO/FKO/src/optsimd.c
iFKO/FKO/src/vars.c

fixed issues with make target of trmm kernel timer

Trmmdev - trmm kernel timer

---

AtlasBase/Clint/trmm-micro.base

fixed trmm copy name for complex precision... tested for both real and complex now.

fixed trmm copy name for complex precision

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas.base
AtlasBase/Clint/micro-kg.base
AtlasBase/Clint/trmm-micro.base

1. Added support for loop peeling and pB hoisting for TRMM kernel
2. Fixed some bugs related to TRMM
Known Issue: 
------------------
1. TimeMMKernel with TRMM not supported yet
2. tested with my old dummy trmmsearch

Trmmdev - Loop peeling and pB hoisting for TRMM

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/atlas.base
AtlasBase/Clint/micro-kg.base
AtlasBase/Clint/trmm-micro.base
AtlasBase/make.base

Here is the summary: 
1. Added codes for TRMM outer loops
2. bugfixed in trmm kernel generator for some special cases.

Trmmdev - Trmm outer loop

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/atlas.base
AtlasBase/Clint/trmm-micro.base
AtlasBase/Clint/trsm-micro.base
AtlasBase/make.base

1. Added TRSM outer loops 
2. fixed some issues on TRMM
3. added code contributor list

Devel - TRSM outer loops

---

AtlasBase/Clint/trmm-micro.base

added the fixed to compare with ATL_VIEW_MAX_KB

compare with ATL_VIEW_MAX_KB to apply trmm_ST

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/atlas.base
AtlasBase/Clint/trmm-micro.base
AtlasBase/make.base

This update will much improve trmm_ST code and it's performance. 
TRMM_ST now performs better (at least similar) than applying solely outer-loop.

Improvement of TRMM ST performance

---

AtlasBase/Clint/atlas-kaux.base
AtlasBase/Clint/micro-kg.base
AtlasBase/Clint/trmm-micro.base

1. Updates on trmmK gen to fixed some cases found from trmm tester
2. FIxed a bug on bitwise op from previous trmm ST redesign 
3. Added syrkK gen for arbitrary MU&NU

update on trmmK generator, bug fixed, syrkK generator for arbitrary mu nu. 

---

AtlasBase/Clint/atlas-kaux.base
AtlasBase/Clint/atlas-maux.base

added support for C2BLK in unrestricted syrk-copy

---

AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/atlas-mmg.base

added support to test TRMM kernels (LL,LU,RL,RU variants).

TRMM Kernel tester 

---

AtlasBase/Clint/atlas-haux.base
AtlasBase/Clint/atlas-iaux.base
AtlasBase/Clint/atlas-kaux.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/atlas-maux.base
AtlasBase/make.base

added fixed C transpose copy 
fixed a typo in makefile

added fixed C transpose copy (blk2CT, CT2blk)

---

AtlasBase/Clint/l3micro.base
extract.c

1. Improved opsyrk upper case using improved outer-loop to minimize TLB problem for large N.  
2. removed some old codes (unnecessary after introducing L2UT) for upper case.

Improved opsyrk upper case 

---

AtlasBase/Clint/atlas-ammm.base
AtlasBase/Clint/atlas-make.base
AtlasBase/Clint/l3micro.base

1. Added unrestricted UR opsyrk (works like general case)
2. Fixed a bug in ursyrk header generation

Unrestricted UR opsyrk implementation

---

AtlasBase/Clint/l3micro.base

fixed some bugs for URSYRK and UROPSYRK which caused failure on opt32

Bug fixes for unrestricted URSYRK 
